version: '3'
services:
  express-user:
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      - mongonet
    ports:
      - 3000:3000

  mongodb_server:
    image: mongo:4.4.5-bionic
    networks: 
      - mongonet
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb_server_vol:/data/db

  mongoexpress:
    image: mongo-express:0.54.0
    networks: 
      - mongonet
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb_server

networks: 
  mongonet:
    driver: bridge

volumes:
  mongodb_server_vol:
    driver: local

